# SkyServe YAML to run multiple Load Balancers in different region.
#
# Usage:
#   1. Register the hosted zone in Route53.
#   2. Go to your DNS manager and setup name servers to Route53.
#   3. `sky serve up examples/serve/external-lb.yaml`.

name: multi-lb

service:
  readiness_probe:
    path: /health
    initial_delay_seconds: 120
  replicas: 4
  # TODO(tian): Change the config to a cloud-agnostic way.
  route53_hosted_zone: aws.cblmemo.net
  # Meta load balancing policy used to select the LB.
  load_balancing_policy: proximate_first
  external_load_balancers:
    - resources:
        cloud: aws
        region: us-east-2
      load_balancing_policy: consistent_hashing
    - resources:
        cloud: aws
        region: ap-northeast-1
      load_balancing_policy: consistent_hashing

resources:
  cloud: aws
  any_of:
    - region: us-east-2
    - region: ap-northeast-1
  ports: 8080
  cpus: 2+

setup: |
  wget https://raw.githubusercontent.com/skypilot-org/skypilot/refs/heads/serve-multi-region-lb/examples/serve/external-lb/server.py
  pip install fastapi uvicorn

run: python3 server.py --port 8080 --length 10
